### ISSUE TITLE
undefined store for fr country

### ISSUE THREAD

**Issue by hsubtil** [Ephigenia/ikea-availability-checker#108]
There is a issue on french contry requests, for exemple : `npx ikea-availability-checker@2.0.0-alpha.1 stock --store 562 80382321` will throw an issue on buCode.

```
return cache[key].find(item => item.store.buCode === buCode);
                                              ^

TypeError: Cannot read properties of undefined (reading 'buCode')
    at /workspace/ikea-web-checker/node_modules/ikea-availability-checker/source/lib/ingka.js:99:47
    at Array.find (<anonymous>)
    at IngkaApi.getStoreProductAvailability (/workspace/ikea-web-checker/node_modules/ikea-availability-checker/source/lib/ingka.js:99:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
```

After investigating there is a undefined store.

![image](https://user-images.githubusercontent.com/30028109/167287289-45fe82c9-7762-4b3f-a7c6-24a12c8344c0.png)

Is it possible to add a small verification on this find ? 

```
return cache[key].find(item => item.store && item.store.buCode === buCode);
```

**Comment by Ephigenia** [comment]
Ah, that must be an unknown store. I'll try to find out which one that it is and add it to the list of stores. Also, I’ll try to prevent this bug from happening in the future.

**Comment by Ephigenia** [comment]
@hsubtil thanks for the bug report!

**Comment by Ephigenia** [comment]
The Store "Nice Saint Isidore" with the buCode 518 was missing in the list of stores. I’ve added the store in the alpha branch which triggered a new release. Should be fine now with: `npx ikea-availability-checker@2.0.0-alpha.3 stock --store 562 80382321`
