### ISSUE TITLE
US search not working

### ISSUE THREAD

**Issue by mitpianoman** [Ephigenia/ikea-availability-checker#11]
Logging a separate issue to follow-on to my previous one, when I try to enter the country code "us", I get the following error:

`% npm run start -- stock --country=us 40413131

> ikea-availability-checker@0.4.0 start /Users/abc/projects/ikea/node_modules/ikea-availability-checker
> node $npm_package_main "stock" "--country=us" "40413131"

(node:16663) UnhandledPromiseRejectionWarning: Error: Unable to receive product 40413131 availability for store 250 status code: 410.
    at /Users/abc/projects/ikea/node_modules/ikea-availability-checker/source/lib/iows2.js:52:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 42)
(node:16663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16663) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Running the same command with other country codes works fine.

**Comment by mitpianoman** [comment]
FYI if I remove store #250 from stores.json, things work fine. It seems to be an exception that applies only to that store.

**Comment by Ephigenia** [comment]
Thanks for the input. I’m going to check this tomorrow

**Comment by Ephigenia** [comment]
Thanks @mitpianoman for finding out which store buCode was wrong. Apparently IKEA changed their Seattle Store to be called "Renton" now … with a different buCode. Fixed in master.
