### ISSUE TITLE
ERR_HTTP_403 with pl country

### ISSUE THREAD

**Issue by okniazik** [Ephigenia/ikea-availability-checker#111]
npx ikea-availability-checker@2.0.0-alpha.2 stock --country pl 80382321

ERR_HTTP_403

**Comment by Ephigenia** [comment]
I was trying to run the command that you provided and get results from all the 10 IKEA stores in Poland. Also you might want to try the latest beta, which is the "alpha.3" … maybe that helps:

```
npx ikea-availability-checker@2.0.0-alpha.3 stock --country pl 80382321
```

**Comment by Ephigenia** [comment]
@okniazik did you had the chance to test it again?

**Comment by okniazik** [comment]
> @okniazik did you had the chance to test it again?

Yeah, looks like it works now. Thank you!

**Comment by Ephigenia** [comment]
@okniazik fantastic! Thank you for your feedback. I’m closing this then.
