### ISSUE TITLE
Error "ERR_HTTP_403" on 2.0.0-alpha.1 version

### ISSUE THREAD

**Issue by allbrus** [Ephigenia/ikea-availability-checker#113]
Please find the attachment with the error displayed. It appears after typing this command: 
npx ikea-availability-checker@2.0.0-alpha.3 stock --country pl 80382321

Tell me how can I fix it, please.

![ERR_HTTP_403](https://user-images.githubusercontent.com/32027656/174249971-408e23b4-9926-4757-baaa-3d8f90df3640.jpg)

**Comment by Ephigenia** [comment]
@allbrus anything new here?

**Comment by allbrus** [comment]
Unfortunately still the same.
![ERR_HTTP_403 (2)](https://user-images.githubusercontent.com/32027656/176345145-41881e2f-58fc-479b-8c65-a27a507dfc6f.jpg)

**Comment by Ephigenia** [comment]
@allbrus thanks for your feedback, as I’m seeing you’re also getting some errors or notifications logged in your shell. It’s still working for me so there must be another reason for this to fail. Maybe I can check if there’s a different API Key used from the PL ikea site. 

Did you manage to get any other query to work or please can you try the following thing to query stuff from other countries?
```
npx ikea-availability-checker@2.0.0-alpha.3 stock --country de 80382321
```

**Comment by mochixo** [comment]
I am also getting the same "ERR_HTTP_403" when using npx ikea-availability-checker@2.0.0-alpha.3 stock --country us 40263848
![image](https://user-images.githubusercontent.com/108594530/177017186-6e935444-1bcd-4d7a-8b98-68c48dacca24.png)

**Comment by allbrus** [comment]
![ikea err http 403 jul2022](https://user-images.githubusercontent.com/32027656/177959694-5e876b1a-78e8-47ba-890d-7ed8b3c5c266.jpg)

Yes, it works for Germany and the Czech Republic, but not for Poland... :(

**Comment by myicq** [comment]
I tried numerous endpoints into IKEA, and everything is shut down. [https://developer.inter.ikea.com › apis](https://developer.inter.ikea.com/apis) is also closed. They did post a job recently for someone to take care of APIs. Not sure what happened, maybe they are restructuring.

**Comment by allbrus** [comment]
It finally works! 
One more question ... Will the columns "restockDate" and "forecast" be available again?
Regards

**Comment by Ephigenia** [comment]
@allbrus the other API doesn’t seem to support restockDate or forecasts as the old one. So it's unlikely that this will come back.

**Comment by allbrus** [comment]
Hello,

Thank you for your concern. 
Restock date and forecast are really important for me. Is it possible that you will try to “crack” it some day?
I would be very grateful for that. 
Please find the attached screenshot. Maybe it will be helpful… or maybe not, remember that I’m not an expert :)


Regards,
Michal Brustman 
Wysłane z iPhone'a
