### ISSUE TITLE
403 Error / Deprecated on Alpha 5

### ISSUE THREAD

**Issue by SemicolonStruggles** [Ephigenia/ikea-availability-checker#130]
The issue from #111 and #113 is back :(

I seem to be having the same issue on 2.0.0-alpha.5

Command
```npx ikea-availability-checker@alpha stock --country=nl 50411990```

Most countries I attempted return a probability=ERR_HTTP_403:
- no
- dk
- ch
- jp
- au
- ca
- hk
- at
- sg
- nl
- es
- fr
- be
- kw
- us
- gb
- it
- hu
- pl
- cz
- sk
- tw
- fi
- my
- cn
- pt
- ro
- ie
- th
- qa
- jo
- hr
- kr
- es

Some countries return a probability=DEPRECATED:
- se
- de

Some countries still work:
- sa
- lt

At first I thought the product might be deprecated in those countries, but that is not the case. I confirmed that the product was still in stock on their website. So is seems to be pointing to something else being deprecated.

Still this does not explain the 403 errors on the other countries.

Hopefully there is a fix. If you need me to do additional testing, I'd be happy to.

**Comment by SemicolonStruggles** [comment]
Upon looking at the code the deprecation probability seems to indicate that the API itself is being deprecated, so nothing that can  be done about that I suppose.

**Comment by Ephigenia** [comment]
Yes, that seems to be an issue from time to time. I don’t have an idea why this is happening. (It works for me though). I started to add a smoketest script that runs a query for almost all countries: https://github.com/Ephigenia/ikea-availability-checker/runs/8292506603

**Comment by SemicolonStruggles** [comment]
It suddenly started working for me now. No idea why. I did try both with and without VPN because in the code I saw you were using the US client ID. I suspected the US client ID would only be valid from US IPs. However, I didn't seem to work anyways. Then I turned the VPN back of and suddenly it started working. Coincidence I am guessing as that doesn't make sense.

Other than that I did install the package globally on my system in the mean time. But again, I can't see how that would matter as npx should have identical results.

I've locally added a console.log to your code so I can see the full error, should the 403 issue occur again. Hopefully I'll be able to provide some more info, should it stop working again.

**Comment by Ephigenia** [comment]
Thank you for your support. The experience you described matches with the other ones having the same issues. It started working for some time and then it failed again. In which country are you located?

**Comment by SemicolonStruggles** [comment]
I am located in the Netherlands. But with VPN I had the same results from Germany, Belgium, Sweden and US.

**Comment by Ephigenia** [comment]
Okay, so then it doesn’t seem to be a country issue then. I wonder if maybe some of the client ids hit a rate limit or something that doesn’t get reported but returns just a 403.

**Comment by Ephigenia** [comment]
Btw, the `ingka.js` file contains two other Client IDs found in the Italian and Dutch website. Maybe next time you hit the error you could try using one of those maybe? (https://github.com/Ephigenia/ikea-availability-checker/blob/alpha/source/lib/ingka.js#L25)

**Comment by SemicolonStruggles** [comment]
Yes I noticed that too. It weird though, because I would expect a client ID to be unique to each client. That does not seem to be the case. Since your code contains the same client ID as the one that I get assigned by the IKEA Netherlands website it seems they use the same client ID for entire countries.

It does seem unlikely though that the 403 are a result of rate limiting, that would mean that a whole (or multiple) country would not be able to access Ikea stock info. Will give it a try though if it happens again.

**Comment by Ephigenia** [comment]
True, right now I don’t have any idea why that happens. Thanks for checking and giving such valuable feedback!

**Comment by Ephigenia** [comment]
Just in case you want to dig deeper, I’ve created a postman collection with the request beeing made: https://www.postman.com/crimson-rocket-271330/workspace/ikea/overview

**Comment by SemicolonStruggles** [comment]
Already stole the endpoint from the chrome network debugger, but thanks anyways :) Will keep you posted if I come across more details regarding the error.

**Comment by Ephigenia** [comment]
Thanks!
