### ISSUE TITLE
Refusing to install package with name "ikea-availability-checker" under a package also called "ikea-availability-checker"

### ISSUE THREAD

**Issue by ss-marie** [Ephigenia/ikea-availability-checker#14]
I have the latest version of ikea-availability-checker and the current recommended version of node.js, 10.16.3. When I run `npm install ikea-availability-checker` per the Installation section of the readme, I get the following error:

> npm ERR! code ENOSELF
> npm ERR! Refusing to install package with name "ikea-availability-checker" under a package
> npm ERR! also called "ikea-availability-checker". Did you name your project the same
> npm ERR! as the dependency you're installing?

**Comment by Ephigenia** [comment]
@ss-marie the error message reads like you’re trying to install the package in a package which is using the same name. Try renaming your package / directory to a different than "ikea-availability-checker".

**Comment by Ephigenia** [comment]
Just to be sure I tried it myself:

```17:59:18 in Development/test/ikea-availability-checker is 📦  v1.0.0 via ⬢ v12.16.1
➜ npm install ikea-availability-checker
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ikea-availability-checker" under a package
npm ERR! also called "ikea-availability-checker". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ephigenia/.npm/_logs/2020-08-17T15_59_23_445Z-debug.log
```

See: https://www.google.com/search?q=code+ENOSELF

**Comment by ss-marie** [comment]
@Ephigenia The directory name was originally the default after cloning from GitHub, "ikea-availability-checker". I renamed the directory but I am still getting the same error. 

I have also tried renaming the package name inside package.json. In that case, the install command succeeds. However then when running the app with `npm run start -- stores at` I get the following error, so I don't think I can resolve the issue by renaming the app.

> ikea-availability-checker-test@0.4.1 start C:\Users\ssmarie\Documents\GitHub\ikea-availability-checker-folder
> node $npm_package_main "stores" "at"
> internal/modules/cjs/loader.js:1083
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\ssmarie\Documents\GitHub\ikea-availability-checker-folder\$npm_package_main'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:923:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []

**Comment by Ephigenia** [comment]
@ss-marie if you cloned the repo you won’t need to install it via `npm install ikea-availability-checker` as the directory already contains the sources of the project.

**Comment by ss-marie** [comment]
@Ephigenia Thanks for your response. Unfortunately even if I leave the package and app name the same as the default after cloning the source, I am unable to run the app using `npm i` and `npm run start -- stores at` as I get the same error above with code MODULE_NOT_FOUND.

**Comment by Ephigenia** [comment]
I only can make assumptions here as I’m not sure what you're planning to do. The things you wrote either read as if you’re planning to contribute something to the project (by mentioning "clone") - on the other hand it seemed like you’re have a modified `package.json` in the cloned project which would conflict with your plans.

If you’re trying to contribute, I assume that you’d do the following:

```
git clone https://github.com/Ephigenia/ikea-availability-checker.git
cd ikea-availability-checker;
npm run start -- --help
```

if you’re trying to install the tool and run in without installing it globally (`npm install -g …`), in that case you’d have to call the alias that is created by npm:

```
mkdir ikea-availability-checker-test;
cd ikea-availability-checker-test;
npm install kea-availability-checker;
node_modules/.bin/ikea-availability;
```

**Comment by Ephigenia** [comment]
It looks like the README.md is not clear about this. I’ll try to make an update to get this more clear.

**Comment by Ephigenia** [comment]
@ss-marie please check the README on the development branch: https://github.com/Ephigenia/ikea-availability-checker/tree/development

Does it get more clear now?
I’d be happy if you could confirm - also that everything is fine for you now - to be able to close this issue?

**Comment by Ephigenia** [comment]
Closing this now.
