### ISSUE TITLE
recurring smoke test (cron)

### ISSUE THREAD

**Issue by Ephigenia** [Ephigenia/ikea-availability-checker#155]

**Comment by Teko012** [comment]
I have created a list of product codes paired with the countries that can be used for checks:

```
AE - 30514791
AT - 00263850
AU - 10514792
BE - 00263850
BG - 30514791
BH - 30514791
CA - 00263850
CE - 30514791 (this is ES but it's the Islands website, same as SP, but a different country code on API from them)
CH - 00263850
CL - 30449908 (different product from the same family)
CN - 10514792
CY - 30514791
CZ - 00263850
DE - 00263850
DK - 00263850
DO - 30514791
EE - 30514791
EG - 30514791
ES - 00263850
FI - 00263850
FR - 00263850
GB - 00263850
GR - 30514791
HK - 10514792
HR - 00263850
HU - 00263850
ID - 10514792
IE - 00263850
IL - 30514791
IN - 10514792
INTSALES - N/A
IS - 30514791
IT - 00263850
JO - 00263850
JP - 10514792
KR - 10514792
KW - 00263850
LT - 00263850
LV - 30514791
MA - 30514791
MX - 30514791
MY - 10514792
NL - 00263850
NO - 00263850
OM - 30514791
PH - 10514792
PL - 00263850
PR - 30514791
PT - 00263850
QA - 00263850
RO - 00263850
RS - 30514791
RU - Closed down
SA - 00263850
SE - 00263850
SG - 10514792
SI - 30514791
SK - 00263850
SP - 30514791 (this is ES but it's the Islands website, same as CE domain, but a different country code on API from them)
TH - 10514792
TR - 30514791
TW - 10514792
UA - 00263850
US - 00263850
```

**Comment by Teko012** [comment]
and currently `au,cn,es,jp,tw` are broken out of the supported countries.

**Comment by Ephigenia** [comment]
Thanks for your input! I’ll check it soon!

**Comment by Teko012** [comment]
Another good candidate could be `90509819`, batteries are sold probably in every store, meanwhile some products are not sold at all in certain stores within the same country, so it won't even show up in the store list.

**Comment by Ephigenia** [comment]
It's okay to have different products in different countries I think. I can switch to the batteries if the smoke-tests need to be updated more often.

**Comment by Ephigenia** [comment]
I think as far as for the alpha the smoke tests are fine now. I left a comment in the smoke tests file that some countries will be added later.

**Comment by Teko012** [comment]
Sounds good, I just wanted to put it as a note. If scraping the stores gets implemented, it should help with catching missing stores.
