### ISSUE TITLE
Error: 'ikea-availability-stock' does not exist

### ISSUE THREAD

**Issue by maxkratz** [Ephigenia/ikea-availability-checker#18]
Hello all,

I've installed the package within a docker container with the following settings:
* ubuntu 20.04
* nodejs v10.19.0
* npm v6.14.4

To install the checker, I've used the following command ``` npm install -g ikea-availability-checker ``` which gives me a warning: 

> _npm WARN notsup Unsupported engine for csv-string@4.0.1: wanted: {"node":">=12.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: csv-string@4.0.1_

Although ``` ikea-availability --help ``` outputs the correct help section of the program, ``` ikea-availability stock at ``` results in an error:

> _/usr/local/lib/node_modules/ikea-availability-checker/node_modules/commander/index.js:925
>         throw new Error(executableMissing);
>         ^
> 
> Error: 'ikea-availability-stock' does not exist
>  - if 'stock' is not meant to be an executable command, remove description parameter from '.command()' and use '.description()' instead
>  - if the default executable name is not suitable, use the executableFile option to supply a custom name
>     at ChildProcess.proc.on (/usr/local/lib/node_modules/ikea-availability-checker/node_modules/commander/index.js:925:15)
>     at ChildProcess.emit (events.js:198:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
>     at onErrorNT (internal/child_process.js:415:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)_

Am I missing something? Any idea where my fault is?

---

Small side notice: ``` ikea-availability-check ``` can not be found as a executable.

**Comment by Ephigenia** [comment]
@maxkratz looks like one of the packages "csv-string" has a minor version that the one mentioned in the package.json. I’ll try to find a solution to that. Please understand that I’m new to this kind of issues.

**Comment by maxkratz** [comment]
@Ephigenia Thank you for looking into this! Would you say that the error at running the ``` stock at ```-command occurs because of the version mismatch?

**Comment by Ephigenia** [comment]
@maxkratz parts of. I think you can fix the issue by updating the node version to >12. 

- "csv-string" is trying to force a node version >12 (https://github.com/Inist-CNRS/node-csv-string/blob/master/package.json#L82)
- "commander" doesn’t do that but might have features / code included that uses features beyond node 6 (https://github.com/Inist-CNRS/node-csv-string/blob/master/package.json#L82)

If you’re able to update the node version that would be the preferred version. Updating and using at least LTE versions (currently node 12) would be recommended. 

I might be checking all the packages and the "engines.node" entry in the [package.json](https://github.com/Ephigenia/ikea-availability-checker/blob/master/package.json#L18)

**Comment by maxkratz** [comment]
@maxkratz I've upgraded to node v12.18.3, which gives me another error while installing the package:

> _npm WARN notsup Unsupported engine for ikea-availability-checker@0.4.4: wanted: {"node":"^10.17","npm":"^6.9.0"} (current: {"node":"12.18.3","npm":"6.14.6"})
> npm WARN notsup Not compatible with your version of node/npm: ikea-availability-checker@0.4.4_

The error at running ``` ikea-availability stock at ``` persists.

**Comment by Ephigenia** [comment]
Yes, that’s right. I can confirm the problem is in the current `package.json` which requires "^10.17" as version which doesn’t get satisfied with the "12.18.3" caused by the "^". I’ve changed the "engine.node" version to be ">10" which now should work. Please try again with the current version of master.

**Comment by maxkratz** [comment]
First of all: I have typos in my previous comments in this issue: ``` ikea-availability stock at ``` -> ``` ikea-availability store at ```.

I've tried two ways of installing it:
* Without cloning the repository and installing it via ``` npm install -g ikea-availability-checker ```. This gives me the same error as before.

> _/usr/bin/ikea-availability -> /usr/lib/node_modules/ikea-availability-checker/source/cli.js
> npm WARN notsup Unsupported engine for ikea-availability-checker@0.4.4: wanted: {"node":"^10.17","npm":"^6.9.0"} (current: {"node":"12.18.3","npm":"6.14.6"})
> npm WARN notsup Not compatible with your version of node/npm: ikea-availability-checker@0.4.4_

(Perhaps the change on master branch was not propagated to npm package distribution or something like that.)

* Cloning the git repo and tried ``` npm run start -- --help ``` and ``` npm run start -- stores at ``` within the repository. This gives me the following error:

> internal/modules/cjs/loader.js:968
>   throw err;
>   ^
> 
> Error: Cannot find module 'commander'
> Require stack:
> - /app/ikea/source/cli.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/app/ikea/source/cli.js:4:15)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/app/ikea/source/cli.js' ]
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ikea-availability-checker@0.4.4 start: `node $npm_package_main "store" "at"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the ikea-availability-checker@0.4.4 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-08-30T15_29_55_312Z-debug.log
> The command '/bin/sh -c npm run start -- store at' returned a non-zero code: 1

As you probably noticed: I'm not really sure about starting the program. Am I missing something?

**Comment by Ephigenia** [comment]
> Perhaps the change on master branch was not propagated to npm package distribution or something like that.

that's what it is, I was hoping you can manage to test it without publishing a new version of the package.

> Cloning the git repo and tried npm run start -- --help and npm run start -- stores at within the repository. This gives me the following error

You can install the version from master by running: 

```
npm install https://github.com/Ephigenia/ikea-availability-checker
```

**Comment by maxkratz** [comment]
Okay, that makes sense to me!

I've tried the command (includig a ```-g```) and got this output:

> /usr/bin/ikea-availability -> /usr/lib/node_modules/ikea-availability-checker/source/cli.js
> npm WARN notsup Unsupported engine for ikea-availability-checker@0.4.4: wanted: {"node":">=10","npm":">6"} (current: {"node":"12.18.3","npm":"6.14.8"})
> npm WARN notsup Not compatible with your version of node/npm: ikea-availability-checker@0.4.4
> 
> + ikea-availability-checker@0.4.4
> added 16 packages from 26 contributors in 5.818s
> Removing intermediate container bf44aea568f3

Does this mean, that my version of npm is too old? I think it is the most recent version out according to their page: https://www.npmjs.com/package/npm

Anyway, if I run the command to get a list of all stores in Austria, I get the following output:

> root@f95270a36f46:/# ikea-availability stores at
> /usr/lib/node_modules/ikea-availability-checker/node_modules/commander/index.js:925
>         throw new Error(executableMissing);
>         ^
> 
> Error: 'ikea-availability-stores' does not exist
>  - if 'stores' is not meant to be an executable command, remove description parameter from '.command()' and use '.description()' instead
>  - if the default executable name is not suitable, use the executableFile option to supply a custom name
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/ikea-availability-checker/node_modules/commander/index.js:925:15)
>     at ChildProcess.emit (events.js:315:20)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)

I've also tried some other variants like ```ikea-availability -- stores at``` but I don't get the desired output. Is the command the right one and can you help me with this behavior?

**Comment by Ephigenia** [comment]
@maxkratz I’ve published a new version v0.4.5 on npm. Please try again. Sorry for the trouble.

**Comment by maxkratz** [comment]
Thank you for responses!

```ikea-availability --version``` gives me ```0.4.6```, therefore the installation of the new version worked without an error:

```
/usr/bin/ikea-availability -> /usr/lib/node_modules/ikea-availability-checker/source/cli.js
+ ikea-availability-checker@0.4.6
added 16 packages from 26 contributors in 1.278s
```

Although the command ```ikea-availability stores at``` gives me the same error as before:
```
root@ae1e950ab2a1:/# ikea-availability stores at
/usr/lib/node_modules/ikea-availability-checker/node_modules/commander/index.js:925
        throw new Error(executableMissing);
        ^

Error: 'ikea-availability-stores' does not exist
 - if 'stores' is not meant to be an executable command, remove description parameter from '.command()' and use '.description()' instead
 - if the default executable name is not suitable, use the executableFile option to supply a custom name
    at ChildProcess.<anonymous> (/usr/lib/node_modules/ikea-availability-checker/node_modules/commander/index.js:925:15)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Ephigenia** [comment]
@maxkratz thanks for testing again, I’ll look into it as soon as I can

**Comment by Ephigenia** [comment]
@maxkratz that’s a known issue with a workaround in the commander package which happens when a package uses differently named sub-command executable files than the main command. That is now fixed with https://github.com/Ephigenia/ikea-availability-checker/commit/da8bc52f78de85828c33a724b25fc5b508ce2d75

Try the new version v0.4.7 and I hope it works

**Comment by maxkratz** [comment]
@Ephigenia I can confirm, that it works as expected now! One sidenote: The program needs ```node-fetch``` installed. (Just in case some other people get a ```MODULE_NOT_FOUND```-error.)

Thank you again for your work and the quick responses!

**Comment by Ephigenia** [comment]
@maxkratz thanks for the hint, somehow i didn’t see that "node-fetch" was added as devDependency, I’ll fix that!
