### ISSUE TITLE
find stor by ID returns wrong type of object

### ISSUE THREAD

**Issue by hugodecasta** [Ephigenia/ikea-availability-checker#25]
```bash
Promise {
  <rejected> AssertionError [ERR_ASSERTION]: Expected first argument countryCode to be a string, instead undefined given.
      at new IOWS2 ([...]/node_modules/ikea-availability-checker/source/lib/iows2.js:52:12)
      at Object.availability ([...]/node_modules/ikea-availability-checker/source/index.js:24:18)
```

It seems that `stores.findById` returns an array of stores, this is why the below code throws an error
```javascript
const store = stores.findById(buCode);
// @TODO handle error when store could not be found
const iows = new IOWS2(store.countryCode);
```
the object `store` is an array, not an object containing `countryCode` resulting in an undefined value, handled by the asserter as an error

**Comment by Ephigenia** [comment]
`stores.findById` takes an array of buCodes and returns all stores found where buCode is matching.
You can use `findOneById` which takes one buCode and returns one Store instead.
