### ISSUE TITLE
IKEA Store missing and error

### ISSUE THREAD

**Issue by remjln** [Ephigenia/ikea-availability-checker#26]
Hello,

I would very like to use this API but I have some issues:
1. This store (https://www.ikea.com/fr/fr/stores/grand-parilly/) is missing in the French stores list (when typing the command `npx ikea-availability-checker -- stores fr` it doesn't show up)
2. Don't know if its related but checking the stock of a product on all the French stores (`npx ikea-availability-checker -- stock --country fr 20388972`) makes an error: `(node:17700) UnhandledPromiseRejectionWarning: Error: Unable to receive product 20388972 availability for store 132 status code: 410 Gone.`

Thanks.

**Comment by Ephigenia** [comment]
1. The Store is not in the [list of stores](https://github.com/Ephigenia/ikea-availability-checker/blob/master/source/data/stores.json). The "store" command requires the store to be known to that list. I’ve added "Grand Parilly" to the list in the "develop" branch and it will be part of the next patch release
2. I’m still checking what’s going on there …

**Comment by Ephigenia** [comment]
The second error happens when the application checks the availability for the product in Paris Ouest, Vélizy which has a totally different and unexpected response format. I created a new issue to soft-handle such cases: #27 until this is resolved I’ll remove Paris Ouest from the list of stores.

**Comment by Ephigenia** [comment]
Found a nice way for handling such issues when requesting stock numbers for a whole country. If there’s a parse error (valid JSON but not the expected structure) there’s a entry in the table with "probability: "PARSE_ERROR".

**Comment by Ephigenia** [comment]
Thanks for noticing both things. I really appreciate it! 

I’ve published a new version: 0.6.2 to npm. Feel Free to use :)
