### ISSUE TITLE
Markdown reporter

### ISSUE THREAD

**Issue by frafra** [Ephigenia/ikea-availability-checker#29]
Hi!
Thanks for sharing the code of your nice project! :-)
I was wondering if you were willing to add a reporter for generating Markdown/CommonMark tables.

**Comment by Ephigenia** [comment]
Sure! How would you like to have it? Please post example

**Comment by frafra** [comment]
I think you can still use `cli-table` but with a different set of characters: https://github.com/cli-table/cli-table3#custom-styles

Tables are an extension of the CommonMark standard, used by GitHub and others: https://github.github.com/gfm/#tables-extension-

You could try with something like this (not tested):
```
var gfm_table = new Table({
  chars: { 'top': '' , 'top-mid': '' , 'top-left': '' , 'top-right': ''
         , 'bottom': '' , 'bottom-mid': '' , 'bottom-left': '' , 'bottom-right': ''
         , 'left': '| ' , 'left-mid': '| ' , 'mid': '-' , 'mid-mid': ' | '
         , 'right': ' |' , 'right-mid': ' |' , 'middle': ' | ' }
});
```

No top, no bottom, `mid` is `-`, `left*` is `| `, right is ` |` and `mid-mid` is ` | `.

**Comment by Ephigenia** [comment]
@frafra instead of implementing this I’d rather share the following approach which combines the output in json format with [jq](https://stedolan.github.io/jq/) and prints a table in markdown format:

```
 npm run -s start -- stock --country at S69022537 --reporter json | \
   jq -r '.[] | [.store.buCode, .store.name, .store.countryCode, .availability.stock, .availability.probability] | @csv' | \
   awk -v FS="," 'BEGIN{print "|bucode|store|name|cc|stock|probability";print "|-|-|-|-|-|"}{printf "|%s|%s|%s|%s|%s|\n",$1,$2,$3,$4,$5}'
```

This would result in:

```
|bucode|store|name|cc|stock|probability
|-|-|-|-|-|
|"387"|"Graz"|"at"|3|"HIGH"|
|"388"|"Haid"|"at"|"0"|"LOW"|
|"273"|"Innsbruck"|"at"|10|"HIGH"|
|"155"|"Klagenfurt"|"at"|3|"HIGH"|
|"386"|"Salzburg"|"at"|"0"|"LOW"|
|"090"|"Wien Nord"|"at"|"0"|"LOW"|
|"085"|"Wien Vösendorf"|"at"|8|"HIGH"|
```

using jq, awk gives you more flexibility in deciding which columns should be shown in which order.

Would that help you or do you still need a markdown output? At least I’d be interested in the purpose of having a markdown output?

**Comment by frafra** [comment]
Sure, jq and awk are wonderful and flexible tools. Still, something that would be missed compared to using `cli-table` is having the columns aligned.
I just wanted to generate a markdown file from time to time to be displayed on a webserver capable of rendering markdown pages, or just using pandoc to generate html pages.

**Comment by Ephigenia** [comment]
@frafra there was no feedback so far from other users, please provide a fork or merge-request …

**Comment by Ephigenia** [comment]
@frafra I’ve enabled github discussions for this repo. Feel free to post your proposal again over there.
