### ISSUE TITLE
bug: France store 518 metadata fix

### ISSUE THREAD

**Issue by alex-oh** [Ephigenia/ikea-availability-checker#339]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/Ephigenia/ikea-availability-checker/issues)

### Current Behavior

The "coordinates" portion of the store metadata for Nice St., Isidore in France reads:
```  
{
    "buCode": "518",
    "name": "Nice St. Isidore",
    "coordinates": [
      7.1950505,15,
      43.7065167
    ],
    "countryCode": "fr"
  },
```

### Expected Behavior

I think store metadata for Nice St., Isidore in France should read:
```
 {
    "buCode": "518",
    "name": "Nice St. Isidore",
    "coordinates": [
      7.1950505,
      43.7065167
    ],
    "countryCode": "fr"
  },
```

### Steps to Reproduce

View stores.json file

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by Ephigenia** [comment]
Thanks for the finding! There's a fix release on the way :D
