### ISSUE TITLE
Add new store

### ISSUE THREAD

**Issue by srokatonie** [Ephigenia/ikea-availability-checker#4]
Hi, I am looking to add store in Ireland. Can you tell how to find a store code?

I should add this to `./data/buCodes.csv` and `./data/stores.json` ?

**Comment by Ephigenia** [comment]
Hi @srokatonie thanks for joining. If there are new stores they should be added to the `./data/stores.json` file. The CSV file next to it is just a legacy file which I created using google docs back then. It will be removed in one of the next versions. 

Also please feel free to create a pull request with the new store in Ireland. You can test if your additions work by calling `npm start stores -- EI` which should list them in the output.

**Comment by srokatonie** [comment]
Hi @Ephigenia,
How do you find Ikea store's buCode? Where do you get it from?

PS. I have an issue with listing stores from ST, ES (and possibly more) - blank result. I will have a look when pulling the repo and adding IE.

**Comment by Ephigenia** [comment]
@srokatonie please provide your changes as a pull request then I can also have a look at it and give better feedback.

Back in the days the BU codes were clearly visible in the source code of the store location dropdown on a product’s detail page. Now it seems to be a bit more difficult by I think Belfast is buCode `038`.

**Comment by srokatonie** [comment]
@Ephigenia I am actually looking for the Dublin's store code. I will contact their support.

**Comment by Ephigenia** [comment]
@srokatonie there’s no need for asking them. 038 is the buCode for the Dublin store. I’m just preparing a pull request myself cause Ireland is not listed anywhere in the code and must be added in various locations.

**Comment by Ephigenia** [comment]
I noticed that Ireland is a special case as some other countries too. They use a different endpoint of the iows API and must be requested and parsed differently. There needs to be more work done to support that. I’m sorry but at this time the integration is not easily done.

**Comment by srokatonie** [comment]
@Ephigenia I'd be happy to contribute, I need this for one of my projects.
