### ISSUE TITLE
Some item's showing Not Found

### ISSUE THREAD

**Issue by g4m3r7ag** [Ephigenia/ikea-availability-checker#57]
**Describe the bug**
Certain items have begun showing "Not Found" when queried via the API but when I search those items on the Ikea website they show up without issue. This is for queries to US stores. I have not checked for other countries. A week ago this issue was not occurring and was showing expected results/restock dates and projections just fine. This does not happen on all items only some. I've mainly been checking for a few still missing pieces from a Sektion Cabinet build. 

**To Reproduce**

Query the availability for item number 00265533 for a US store(s). It will show not found. However if you search that item number on the Ikea US website, it shows the proper item, a 24" Utrusta shelf. 

**Expected behavior**
Display the item results when queried via API

**Screenshots**

![Screenshot from 2021-09-08 23-11-43](https://user-images.githubusercontent.com/46694420/132616349-cc9ed68d-8fdf-4198-aedf-de7c025308b1.png)

https://www.ikea.com/us/en/p/utrusta-shelf-white-00265533/

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ephigenia** [comment]
Not found may be misleading here as this error code is shown if the api replies with an unexpected http response code. I will need to debug the underlying API request to guess further details on this.

**Comment by g4m3r7ag** [comment]
Some more ids

10467941
30467935
10467936

**Comment by g4m3r7ag** [comment]
Those items are all returning results now.

**Comment by Ephigenia** [comment]
Okay, thanks for checking, that seemed to be a temporary issue then.
