### ISSUE TITLE
Would this work for ikea germany?

### ISSUE THREAD

**Issue by bojomojo** [Ephigenia/ikea-availability-checker#60]
Would this work for ikea germany?

**Comment by Ephigenia** [comment]
The IKEA IOWS API supports various countries. You can find a list in the project’s [README](https://github.com/Ephigenia/ikea-availability-checker#features). Germany is one of them.

Example showing availability for all german stores:

```
npm run start -s -- stock --country de 40413131
```

you can also specify a city name:

```
npm run start -- stock --store=Berlin 40413131
```

As this is no issue I’d recommend next time posting this in [Discussions](https://github.com/Ephigenia/ikea-availability-checker/discussions).
