### ISSUE TITLE
Home Delivery Availability

### ISSUE THREAD

**Issue by apphancer** [Ephigenia/ikea-availability-checker#73]
In an age where more and more shopping happens online, I think many people will find it useful to check Home Delivery Availability.

Is there currently a way to check for Home Delivery Availability within a country? If not, would be possible to have this option added if IKEA provides this information through their endpoints?

I think this works slightly differently as some countries (GB, DE...) require a postcode to check for Home Delivery Availability.

**Comment by Ephigenia** [comment]
That topic is mentioned quite sometimes here. There are other solutions that use the cart API … check the discussions thread over here: https://github.com/Ephigenia/ikea-availability-checker/discussions/42
