### ISSUE TITLE
AU Stores

### ISSUE THREAD

**Issue by aythan** [Ephigenia/ikea-availability-checker#78]
Hi there,

Looks like not all AU stores are returned from executing ikea-availability stores au

countryCode │ country   │ buCode │ name        │
├─────────────┼───────────┼────────┼─────────────┤
│ au          │ Australia │ 451    │ Canberra    │
├─────────────┼───────────┼────────┼─────────────┤
│ au          │ Australia │ 460    │ North Lakes │
├─────────────┼───────────┼────────┼─────────────┤
│ au          │ Australia │ 919    │ Logan       │

Adelaide store is 557.

ikea-availability -- stock --store=557 10335192

Yet cannot hit it (no stores found), any ideas?

**Comment by Ephigenia** [comment]
@aythan I can add the Adelaide store later today …

**Comment by aythan** [comment]
> @aythan I can add the Adelaide store later today …

You absolute legend!

**Comment by Ephigenia** [comment]
I found there are even more stores in Australia … I’ll try to add them all

**Comment by Ephigenia** [comment]
@aythan when did you try out to get the availabilities for the Australian stores? I’m getting a deprecation error for all of them now
