### ISSUE TITLE
Can this give stock of online distribution center?

### ISSUE THREAD

**Issue by wootwoot1234** [Ephigenia/ikea-availability-checker#8]
I'm wanting to buy some smart blinds and the inventory online keeps showing up as available but when you go to buy it, the website says it's out of stock.  What I've noticed is that if you keep checking, more stock will become available and you are able to make the purchase.  Is it possible to use this tool to check that inventory?

**Comment by Ephigenia** [comment]
@wootwoot1234 Thanks for finding out. Can you please provide some more information for me to be able to reproduce the effect. Please provide the product number and URL to the page that you’re checking.

**Comment by wootwoot1234** [comment]
Thanks, it would be super helpful to have a way to check the online inventory of these items.  It always says it's available on the product page but when you go to buy it, it often says it can't deliver it.

This is one of the items I'm looking at (smart blinds 38").  Currently says it's in stock online.  If you add it to your cart it will also offer delivery. 

https://www.ikea.com/us/en/p/fyrtur-blackout-roller-blind-wireless-battery-operated-gray-00417466/

This one (smart blinds 34") is also showing up as available online but when you add it to the cart and try to buy it says it's not available for delivery.

https://www.ikea.com/us/en/p/fyrtur-blackout-roller-blind-wireless-battery-operated-gray-50417464/

I'm hoping your tool can helo check the online inventory and if it can be delivered.

**Comment by Ephigenia** [comment]
I’m still having trouble to reproduce the issue. I’m from Germany so maybe I’m not seeing the same effect as you do. I tried to put the blinds in the cart and continue to order but can’t see a message that they cannot be delivered anymore.

**Comment by wootwoot1234** [comment]
Here are examples of the blinds that can't be delivered and another product that can.  You can only see that they can not be delivered once you add them to your cart and try to purchase them.

Blinds:
![Screen Shot 2020-06-28 at 11 08 39 AM](https://user-images.githubusercontent.com/419609/85952587-fdbf5e00-b92f-11ea-90a3-16cf7a73deb8.png)

Other product that is in stock (Trofast shelves)
![Screen Shot 2020-06-28 at 11 09 38 AM](https://user-images.githubusercontent.com/419609/85952585-fc8e3100-b92f-11ea-8f7a-d9f70dedbe0e.png)

**Comment by Ephigenia** [comment]
Thanks for the screenshots, I'll try to find something.

**Comment by wootwoot1234** [comment]
Thank you, I really appreciate it!

**Comment by Ephigenia** [comment]
@wootwoot1234 can you please try to re-run the command you did last time with the latest version please and report the exact call and the result? I made some updates which with low probability may have fixed this issue …

I’m still assuming you’re running something like:

```
npm run start -- stock --country us 50417464
```

and

```
npm run start -- stock --country us 5041746
```


Please provide alternate command that you’re using …

**Comment by cdrfun** [comment]
At first, I want to thank you for the great work! Perhaps I can help with the issue, as I had the same question, and I'm also located in Germany. 
If I currently want to buy this Item, it says available at the truck icon:
![grafik](https://user-images.githubusercontent.com/146877/104419080-3e9f5d00-5578-11eb-9579-eacac73056bf.png)

After adding my other items I go to checkout:
![grafik](https://user-images.githubusercontent.com/146877/104419243-79a19080-5578-11eb-88ca-c4027b0c3f54.png)

Afterwards I have to enter the zip code to where my order shall be delivered:
![grafik](https://user-images.githubusercontent.com/146877/104419356-a5bd1180-5578-11eb-8b37-17f495f30a76.png)

And after all of this the website tells me the item is not available:
![grafik](https://user-images.githubusercontent.com/146877/104419413-b9687800-5578-11eb-8164-c6b6fe76f93e.png)

This seems not related to the stock of the stores.

**Comment by Ephigenia** [comment]
Thanks for the additional info. I’ll have a look when I find time but I guess that the information for delivery is completely different from the store availability.

**Comment by vrslev** [comment]
> I guess that the information for delivery is completely different from the store availability.

You are not wrong. This uses different API. I didn't find anything interesting in IOWS and Mobile API responses. 
Also noteworthy: in my country (Russia) have appeared new warehouses specially for online shopping. And IKEA now uses both these warehouses and ordinary shops.

**Comment by Ephigenia** [comment]
@vrslev thanks for checking.

I’m not sure on how to continue with this. As me and you haven’t found real clues on how to get information from that new unknown API I’d like to close this as it’s not clear on how to solve this.

**Comment by Ephigenia** [comment]
@vrslev please check https://github.com/Ephigenia/ikea-availability-checker/discussions/36

**Comment by vrslev** [comment]
Couple of days ago I tried to reproduce result of unavailable items with this API and didn't have any luck. Results are different from the one that is in cart
