### ISSUE TITLE
403 for all request to BE stores

### ISSUE THREAD

**Issue by nicoske** [Ephigenia/ikea-availability-checker#93]
It seems that all request to Belgian stores are failing with a 403. I did tested the same request using other countries (it, be, fr, de) and they worked. Not sure what the problem is.

```
$ ikea-availability stock --country be 70346932
/usr/local/lib/node_modules/ikea-availability-checker/source/lib/iows2.js:114
      throw new errors.IOWS2ResponseError(error);
            ^

IOWS2ResponseError: Unable to receive product 70346932 availability for store 482 status code: 403 undefined using url: /retail/iows/be/fr/stores/482/availability/ART/70346932
    at IOWS2.fetch (/usr/local/lib/node_modules/ikea-availability-checker/source/lib/iows2.js:114:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

```
nico@kit:~$ ikea-availability stock --store 423 70346932
/usr/local/lib/node_modules/ikea-availability-checker/source/lib/iows2.js:114
      throw new errors.IOWS2ResponseError(error);
            ^

IOWS2ResponseError: Unable to receive product 70346932 availability for store 423 status code: 403 undefined using url: /retail/iows/be/fr/stores/423/availability/ART/70346932
    at IOWS2.fetch (/usr/local/lib/node_modules/ikea-availability-checker/source/lib/iows2.js:114:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by Ephigenia** [comment]
Thanks for finding this. I can confirm that this also happens on my machine. I’ll try to find out what’s going on there.

**Comment by Ephigenia** [comment]
Requesting the availability for Belgian stores results in 403 status messages. In the past, this was temporary and gone after a few days. It also could be that this is a permanent issue as IKEA seems to change its APIs.

**Comment by sammyke007** [comment]
I still seem to get 403 error in Belgian stores...
Checking in NL (Netherlands) works perfectly fine however.

![image](https://user-images.githubusercontent.com/33524412/159220875-07428d04-38c2-405b-b09b-407bad7f359a.png)

**Comment by Ephigenia** [comment]
@sammyke007 I can confirm that I get the same results and the product number is okay. I’ll investigate this further as soon I find some time. I can also confirm that no other randomly used product number worked, and also received a 403. Maybe that is a bigger issue.

**Comment by BHSPitMonkey** [comment]
I recently started having the same issue too (for all US stores I've tried, and one I was successfully periodically checking previously). Seems like they've broken public access to the API?
